### ISSUE TITLE
Allow bundle to install in SF 4.0 ? 

### ISSUE THREAD

**Issue by tabbi89** [borNfreee/tactician-domain-events-bundle#8]
Is there any reason why we couldn't add SF 4.0 dependencies ?

"symfony/http-kernel": "^2.8|^3.0|^4.0",
"symfony/dependency-injection": "^2.8|^3.0|^4.0",

?

**Comment by maks-rafalko** [comment]
Thank you, I will look into this in the next few days. Feel free to submit a PR

**Comment by tabbi89** [comment]
Hi I just wanted to submit PR but I've realized that there are no tests. Maybe it would be wise to add a functional test with whole bundle setup something similar to https://github.com/Behat/Symfony2Extension/tree/master/testapp ?

**Comment by maks-rafalko** [comment]
Having a functional test definitely would be a great thing

**Comment by maks-rafalko** [comment]
Implemented in https://github.com/borNfreee/tactician-domain-events-bundle/pull/9
